package com.deliverly.login;


import com.deliverly.main.admin.AdminMenu;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;
import com.deliverly.main.customer.CustomerMenu;
import com.deliverly.main.manager.ManagerMenu;
import com.deliverly.main.runner.RunnerMenu;
import com.deliverly.main.vendor.VendorMenu;

/**
 *
 * @author natsu
 */
public class LoginMenu extends javax.swing.JFrame {
    
    private static String username;
    public LoginMenu() {
        initComponents();
        this.pack();
    }
    public void setUsername(String username){
        LoginMenu.username = username;
    }
    
    public String getUsername(){
        return LoginMenu.username;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        WestPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        UserLabel = new javax.swing.JLabel();
        usernamelogo = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        PassLabel = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        passwordlogo = new javax.swing.JLabel();
        LoginButton = new javax.swing.JButton();
        ClearButton = new javax.swing.JButton();
        ForgotPassword = new javax.swing.JLabel();
        EastPanel = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(840, 500));

        WestPanel.setBackground(new java.awt.Color(255, 255, 255));
        WestPanel.setPreferredSize(new java.awt.Dimension(400, 100));
        WestPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridLayout());

        jLabel3.setFont(new java.awt.Font("Nirmala UI", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Welcome To Deliverly");
        jLabel3.setPreferredSize(new java.awt.Dimension(205, 30));
        jPanel1.add(jLabel3);

        WestPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 396, 100));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UserLabel.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        UserLabel.setForeground(new java.awt.Color(0, 0, 0));
        UserLabel.setText("Username or Email");
        jPanel3.add(UserLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 200, 29));

        usernamelogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/free-user-icon-3296-thumb (1).png"))); // NOI18N
        jPanel3.add(usernamelogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        usernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameFieldActionPerformed(evt);
            }
        });
        jPanel3.add(usernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 200, 37));

        PassLabel.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        PassLabel.setForeground(new java.awt.Color(0, 0, 0));
        PassLabel.setText("Password");
        jPanel3.add(PassLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 200, 29));

        password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordKeyPressed(evt);
            }
        });
        jPanel3.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 200, 35));

        passwordlogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/hiclipart.com.png"))); // NOI18N
        jPanel3.add(passwordlogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        LoginButton.setBackground(new java.awt.Color(255, 255, 255));
        LoginButton.setFont(new java.awt.Font("Nirmala UI", 3, 14)); // NOI18N
        LoginButton.setForeground(new java.awt.Color(0, 0, 0));
        LoginButton.setText("Login");
        LoginButton.setMaximumSize(new java.awt.Dimension(30, 30));
        LoginButton.setMinimumSize(new java.awt.Dimension(30, 30));
        LoginButton.setPreferredSize(new java.awt.Dimension(30, 30));
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });
        LoginButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LoginButtonKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                LoginButtonKeyTyped(evt);
            }
        });
        jPanel3.add(LoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 70, -1));

        ClearButton.setBackground(new java.awt.Color(255, 255, 255));
        ClearButton.setFont(new java.awt.Font("Nirmala UI", 3, 14)); // NOI18N
        ClearButton.setForeground(new java.awt.Color(0, 0, 0));
        ClearButton.setText("Clear");
        ClearButton.setMaximumSize(new java.awt.Dimension(30, 30));
        ClearButton.setMinimumSize(new java.awt.Dimension(30, 30));
        ClearButton.setPreferredSize(new java.awt.Dimension(30, 30));
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });
        jPanel3.add(ClearButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 70, -1));

        ForgotPassword.setBackground(new java.awt.Color(255, 255, 255));
        ForgotPassword.setFont(new java.awt.Font("Nirmala UI", 3, 14)); // NOI18N
        ForgotPassword.setForeground(new java.awt.Color(0, 51, 255));
        ForgotPassword.setText("Forgot Your Password?");
        jPanel3.add(ForgotPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 200, 29));

        WestPanel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 400, 400));

        getContentPane().add(WestPanel, java.awt.BorderLayout.WEST);

        EastPanel.setBackground(new java.awt.Color(204, 255, 255));
        EastPanel.setMaximumSize(new java.awt.Dimension(200, 200));
        EastPanel.setMinimumSize(new java.awt.Dimension(200, 200));
        EastPanel.setPreferredSize(new java.awt.Dimension(440, 500));
        EastPanel.setLayout(new java.awt.GridLayout());

        Logo.setForeground(new java.awt.Color(0, 0, 0));
        Logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Logo.setIcon(new javax.swing.ImageIcon("C:\\Users\\natsu\\Downloads\\black_on_trans-resized.png")); // NOI18N
        EastPanel.add(Logo);
        Logo.getAccessibleContext().setAccessibleName("");

        getContentPane().add(EastPanel, java.awt.BorderLayout.EAST);

        setSize(new java.awt.Dimension(855, 509));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameFieldActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        logIn();   
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
        usernameField.setText("");
        password.setText("");
    }//GEN-LAST:event_ClearButtonActionPerformed

    private void LoginButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LoginButtonKeyPressed
        // nothing
    }//GEN-LAST:event_LoginButtonKeyPressed

    private void LoginButtonKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LoginButtonKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginButtonKeyTyped

    private void passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){
        LoginButtonActionPerformed(null);
    }
    }//GEN-LAST:event_passwordKeyPressed
    
    public void logIn() {
        try{
            boolean userFound = false;
            File users_file = new File("src//data//users.txt");
            FileReader fr = new FileReader(users_file);
            BufferedReader br = new BufferedReader(fr);
            String user;

            String input_username = usernameField.getText();
            String input_password = new String(password.getPassword());
            
            while((user=br.readLine())!=null){
                String saved_username = user.split(";")[1];
                String saved_email = user.split(";")[6];
                String saved_password = user.split(";")[2];
                
                if(input_username.equals(saved_username) && input_password.equals(saved_password) ||
                        input_username.equals(saved_email) && input_password.equals(saved_password)){
                    userFound = true;
                    setUsername(usernameField.getText());
                    JOptionPane.showMessageDialog(null, "Successfully login");
                    break;
                }
            }
            if(!userFound){
                JOptionPane.showMessageDialog(
                null, "Unable to login! Enter valid Username and Password!");
            } else {
                this.dispose();                
                if(user.split(";")[0].contains("CUS") == true){
                    new CustomerMenu().setVisible(true);
                }
                else if(user.split(";")[0].contains("RNR") == true){
                    new RunnerMenu().setVisible(true);
                }
                else if(user.split(";")[0].contains("VEN") == true){
                    new VendorMenu().setVisible(true);
                }
                else if(user.split(";")[0].contains("ADM") == true){
                    new AdminMenu().setVisible(true);
                }
                else if(user.split(";")[0].contains("MNG") == true){
                    new ManagerMenu().setVisible(true);
                }
                
            }
        }catch(IOException e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ClearButton;
    private javax.swing.JPanel EastPanel;
    private javax.swing.JLabel ForgotPassword;
    private javax.swing.JButton LoginButton;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel PassLabel;
    private javax.swing.JLabel UserLabel;
    private javax.swing.JPanel WestPanel;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel passwordlogo;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernamelogo;
    // End of variables declaration//GEN-END:variables
}
